### ISSUE TITLE
Fix wrong writing in documentation

### ISSUE THREAD

**Issue by riibeirogabriel** [riibeirogabriel/learningOrchestra#61]
look at documentation and make suggestions to increase the quality of docs.

**Comment by riibeirogabriel** [comment]
@antoniouaa do you can get this issue?

**Comment by antoniouaa** [comment]
I can take a look

**Comment by riibeirogabriel** [comment]
Good, you can read the md files in /docs path, all suggestions are very welcome!

**Comment by UdokaVrede** [comment]
is this open for hacktoberfest?

**Comment by riibeirogabriel** [comment]
Hi @antoniouaa also, but @antoniouaa already get this  issue, i can get up new issues if you desire contribute whit this repo.

**Comment by riibeirogabriel** [comment]
@antoniouaa thanks!
