### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by antoniouaa** [riibeirogabriel/learningOrchestra#64]
Hello, I saw your recent post in the Hacktoberfest discord server and found your repo.

The repository doesn't have a CONTRIBUTING.md file guiding new users towards meaningful contributions. Would you mind adding one?

**Comment by riibeirogabriel** [comment]
Hi @antoniouaa i forget this addition, do you can do this? thanks!

**Comment by riibeirogabriel** [comment]
@antoniouaa Do you have interest to contribute regularly with this project?

**Comment by antoniouaa** [comment]
Hi, unfortunately this is a bit too advanced for me, best I can do right now is make the Contrib file

**Comment by riibeirogabriel** [comment]
No problems, if also can get the docs issue it will be great, i don't have a good english.

**Comment by riibeirogabriel** [comment]
and please give a star to project to help spreading.

**Comment by riibeirogabriel** [comment]
Thanks!
