### ISSUE TITLE
Remove unused dependencies in microservices

### ISSUE THREAD

**Issue by riibeirogabriel** [riibeirogabriel/learningOrchestra#67]
There are python packages in requirements.txt of each microservice which don't are uses, we need remove this packages.

**Comment by StephanieGreenberg** [comment]
Can I be assigned to this?

**Comment by StephanieGreenberg** [comment]
To me it looks like all dependencies are used.

**Comment by riibeirogabriel** [comment]
Hi, in Model Builder microservice, the numpy package seems which not used, you need remove this package from requirements.txt and from modelbuilder.py
