### ISSUE TITLE
Get an insight to make the readme project more attractive

### ISSUE THREAD

**Issue by riibeirogabriel** [riibeirogabriel/learningOrchestra#70]
Currently there are people which don't understand the project purpose, and leave the repo, if you can give a insight to make the project more attractive, please let a comment.

**Comment by riibeirogabriel** [comment]
Please read the docs before gives a suggestion.

**Comment by banjtheman** [comment]
Need to show the output this tool can do,  and why it's cool. No one cares about an architecture diagram 
Show how people can use the program quickly as well.
i.e

```
pip install my program
pyhton my_progrom
cool output...
```

**Comment by navendu-pottekkat** [comment]
Here are some changes to the README I suggest:

- [ ] Add a header image

- [ ] Add install instructions

- [ ] Add usage instructions

- [ ] Add usage examples

- [ ] Add all contributors

Some other stuff:

- [ ] Add issue and PR templates

- [ ] Add code of conduct

@riibeirogabriel Do let me know if these changes could work and I will make a PR!

**Comment by Nish251103** [comment]
I can help you with adding a menu driven program which will make it much easier for the the user to interact. Kindly assign me the issue.

**Comment by izharqadeer** [comment]
Firstly, make the project users friendly so that every one including beginners can understand the code and don't forget to give a short description about the project.

**Comment by riibeirogabriel** [comment]
@banjtheman did you see the learningOrchestra docs? (https://riibeirogabriel.github.io/learningOrchestra/usage/)
in each microservice section there is an example of usage, and in python package (https://pypi.org/project/learning-orchestra-client/) there is an example of usage with titanic dataset challengue from Keagle.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat thanks! did you see the docs?  (https://riibeirogabriel.github.io/learningOrchestra/usage/), some tasks of your list i think which already done.

**Comment by riibeirogabriel** [comment]
@banjtheman I will remove the architecture image, thanks!

**Comment by Nirali0029** [comment]
Personally from my experience I can say, many people don't understand the project purpose due to the difficult words used. Imagine for a beginner who just started programming, how can you expect to understand all terms. And once, if you don't understand  a word, your interest in it starts decreasing and eventually you leave it. So, along with readme. add in bottom meaning of some difficult terms like what cluster means for your repo and so on..

**Comment by riibeirogabriel** [comment]
@Nirali0029 thanks! I think which you is right, but if i add all words means, the readme can be bigger, but perhaps i can add a hyperlink in each word directing to a site explaining that mean.

**Comment by navendu-pottekkat** [comment]
> @navendu-pottekkat thanks! did you see the docs? (https://riibeirogabriel.github.io/learningOrchestra/usage/), some tasks of your list i think which already done.

Yes, I saw that. But that is in a separate doc website right. Maybe a quick guide on all that on the README? 

Here is a project I am working on https://github.com/nsfw-filter/nsfw-filter , so something like this. IDK just a suggestion.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat Do you could make a PR? it seems good!

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel sure, i will make one by EOD

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat please, if you can, make the changes which you think good, based on your wishlist.

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel I have some questions that need clarifications. Do the Python package and the shell script differ in function?

From what I understand, we have a python package and a shell script that can be deployed and we should provide docs for both?

**Comment by riibeirogabriel** [comment]
Hi @navendu-pottekkat, the shell script makes the deploy of the software, you can see how use here (https://riibeirogabriel.github.io/learningOrchestra/install/) and the python package, is a way to use the Learning Orchestra without use the REST API of each microservice, the python package is a feature, and the shell script is necessary to deploy the learningOrchestra, do you understand?

**Comment by riibeirogabriel** [comment]
I set the Python package docs in PiP repo to don't replicate the docs, the PiP need a readme.

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Now I get it. I have started a draft PR also, I will try to finish it today itself. Also looking forward to help you promote the project after I complete.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat I see this draft, i like this, it will be good, i am also trying promote this project, it did takes a long time of development and there are more funcionatilites to be added.

**Comment by navendu-pottekkat** [comment]
> @navendu-pottekkat I see this draft, i like this, it will be good, i am also trying promote this project, it did takes a long time of development and there are more funcionatilites to be added, and thanks!

I love contributing and seeing open source projects getting big! It is great feeling after you have done such hard work. I will help as much as I can.

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel In this [instruction](https://riibeirogabriel.github.io/learningOrchestra/install/), you have not provided this.

In the VM you would have to clone this repo first and then run the `run` script right?

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat yes, in manager docker swarm machine, ok?

**Comment by riibeirogabriel** [comment]
I forget to cite this, i will fix in site docs

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat thank you very much!

**Comment by riibeirogabriel** [comment]
Now i think which users will better understanding of learning Orchestra objective and how usage.

**Comment by navendu-pottekkat** [comment]
I will also make some other PRs that would help and make a ticket regarding the promotion

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat very nice, feel free to make any suggestions!
