### ISSUE TITLE
Menu driven Program 

### ISSUE THREAD

**Issue by Nish251103** [riibeirogabriel/learningOrchestra#71]
I can help you with adding a menu driven program which will make it much easier for the the user to interact. Kindly assign me the issue.

**Comment by riibeirogabriel** [comment]
@Nish251103  sorry i yet don't understand, you think to make a GUI for learningOrchestra?

**Comment by Nish251103** [comment]
> @Nish251103 sorry i yet don't understand, you think to make a GUI for learningOrchestra?

i mean adding a mean which consists of the available machine learning tools and also apart from that i can add linear regression algorithm

**Comment by riibeirogabriel** [comment]
It seems good, do you think wich these menu shows in repo readme or in learningOrchestra docs (https://riibeirogabriel.github.io/learningOrchestra/)?

**Comment by Nish251103** [comment]
> It seems good, do you think wich these menu shows in repo readme or in learningOrchestra docs (https://riibeirogabriel.github.io/learningOrchestra/)?
i could write a python program for it

**Comment by riibeirogabriel** [comment]
I think which already was  created  these python program with all options, did you think a program like this (https://pypi.org/project/learning-orchestra-client/) ?

**Comment by Nish251103** [comment]
> I think which already was created these python program with all options, did you think a program like this (https://pypi.org/project/learning-orchestra-client/) ?

oh something like this. So as its already there so can i help you with something with python language. If you have any task to be done which requires my python knowledge. Thank you

**Comment by riibeirogabriel** [comment]
@Nish251103 the python package is showed in docs, but if you don't saw this, this docs seems not good to new users.
There are some python tasks, later i will publish them and notify you, ok? please give a star to help spread the project.

**Comment by Nish251103** [comment]
> @Nish251103 the python package is showed in docs, but if you don't saw this, this docs seems not good to new users.
> There are some python tasks, later i will publish them and notify you, ok? please give a star to help spread the project.

sure, Thank you. I would be happy to contribute and ofcourse it deserves a star
